#!/bin/bash
set -e

echo "Setting up Bundler"
bundle config build.nokogiri --use-system-libraries

echo "Installing gems"
bundle check || bundle install

echo "Running db:test:prepare"
bundle exec rake db:test:prepare

echo "Running tests"
bundle exec rspec
